# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7380b8fc05daceba88647da3f19f8957684f3e77d646b3ff3c7e78f50fe87f74b4cd7f34fdd56137776963d7b7637ad5105d4bacdf582d2efae99298eb9acc06

test:
  secret_key_base: 53331559aeb245c83d591896b6239a56e3601f0f77cae48cbc5c007f4096d916bbd2adfd869a29196f6df47c2cba3853bfe878bd2f092215ce3abb53cb5b4716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
